import Head from 'next/head'
import {useState} from "react"


export default function Home() {
  const [inputData,setInputData]=useState({
    data:"",
    tick:false
  })
  const [todoArray,setTodoArray]=useState([])
  const [displayedArray,setDisplayedArray]=useState([])
  const handleChange=(e)=>{
    const {name,value,checked,type}=e.target
    setInputData(prev=>{
      return{
        ...prev,
      [name]:type==="checkbox"?checked:value //computed property
      }
    })
  }
  const handleClick=()=>{
    todoArray.push(inputData.data)
    const styles={
      color: inputData.tick?"red":"black"
    }
    if (inputData.data){ 
      const mappedArray=todoArray.map(element=>(
        <div style={styles} className='mapped-div' key={element}>
          {element}
          </div>
      ))
      setDisplayedArray(mappedArray)
    }else{
      console.log(1)
      todoArray.pop()
    }
    
    console.log(todoArray)
    console.log(inputData.tick)
  }
  const clearTodo = () =>{
    setTodoArray([])
    setDisplayedArray([])
    setInputData(prev=>{
      return {
        ...prev,
        data:""
      }
    })
  }
  return (
    <div >
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <section>
          <h1>TODO</h1>
          <div className=""><input onChange={handleChange} type="text" name='data' value={inputData.data} /></div>
          <div className="">
            <button onClick={handleClick}>Add Todo</button>
            {/* <button >Clear Todo</button> */}
          </div>
          {displayedArray}
          {displayedArray.length>0&&<div className="bottom">
            <div className="">{displayedArray.length} items left</div>
            
            <div onClick={clearTodo} className="clear">Clear Completed</div>
          </div>}
        </section>
    </div>
  )
}

//have a todo array in state that is empty initially
//once theh todo is enterered in the input, the todo array should push the input value, then the array should be looped over to render the todo available
//always remember not to mutate state directly, mutate state using the setter function
